version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Instalar dependencias
          command: npm install

      - run:
          name: Construir imagen Docker
          command: docker build -t integracion-api:circleci .

      - run:
          name: Verificar imagen Docker
          command: docker images | grep integracion-api

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build-test